version: "2"
services:
  kibana_test:
    image: kibana:7.12.0
    container_name: kibana_test
    restart: always
    ports:
      - 5601:5601
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
