version: "2"
services:
  kibana:
    image: kibana:7.12.0
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - /etc/localtime:/etc/localtime:ro
      - ../cert:/usr/share/elasticsearch/config/certificates
    network_mode: host
