---
#-------------network------------------
network.host: 0.0.0.0
#--------------------------------------

#------------node_settings-------------
node.name: es01
#--------------------------------------

#-----------cluster_settings-----------
cluster.name: "elk"
discovery.seed_hosts: [ "es01", "es02", "es03" ]
discovery.zen.minimum_master_nodes: 2
cluster.initial_master_nodes: [ "es01", "es02" , "es03" ]
#--------------------------------------

#------------memory--------------------
bootstrap.memory_lock: true
indices.memory.index_buffer_size: 30%
#--------------------------------------

#------------x-pack--------------------
#This deprecated setting has no effect
xpack.monitoring.enabled: true
#--------------------------------------
#xpack.security.enabled: true
#xpack.security.transport.ssl.enabled: true
xpack.monitoring.collection.enabled: true

<<<<<<< HEAD
#xpack.license.self_generated.type: "trial"
=======
#x-pack security
#xpack.monitoring.enabled: "true"
#xpack.security.enabled: "true"
#xpack.security.transport.ssl.enabled: "true"
xpack.monitoring.collection.enabled: "true"
>>>>>>> 2b59df72751cbe41f6085b6c7e0644b0cb519b8b


#------------disabled------------------
#discovery.type: single-node
#--------------------------------------
