---
network.host: 0.0.0.0
#discovery.type: single-node

cluster.name: "elk"
node.name: es01
discovery.seed_hosts: [ "es01", "es02", "es03" ]
cluster.initial_master_nodes: [ "es01", "es02", "es03" ]
bootstrap.memory_lock: "true"
discovery.zen.minimum_master_nodes: 2
indices.memory.index_buffer_size: 30%


#x-pack security
#xpack.monitoring.enabled: "true"
#xpack.security.enabled: "true"
#xpack.security.transport.ssl.enabled: "true"
xpack.monitoring.collection.enabled: "true"

