version: "2"
services: 
  logstash:
    image: logstash:7.12.0
    container_name: logstash
    hostname: logstash
    restart: always
    ports:
      - 5044:5044
      - 9600:9600
    volumes:
      - ./config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./pipeline:/usr/share/logstash/pipeline
#      - ../cert:/usr/share/logstash/config/certificates
    network_mode: host
