---
#----------node--------------
server.name: "kibana"
server.host: "0.0.0.0"
#----------------------------

#------settings_for_es-------
elasticsearch.hosts: [ "http://es01:9200", "http://es02:9200", "http://es03:9200" ]
elasticsearch.username: "elastic"
elasticsearch.password: "QWE123qwe"
<<<<<<< HEAD
#----------------------------

#--------x-pack--------------
#xpack.security.enabled: true
#----------------------------


=======
monitoring.enabled: true
>>>>>>> 2b59df72751cbe41f6085b6c7e0644b0cb519b8b
