---

- name: test
  hosts: all
  become: yes


  tasks:
   - shell: uptime
     register: result
   - debug:
      var: result 
  

   - name: Installl for ubuntu
     apt : name=apache2 state=latest
     when: ansible_os_family != "RedHat"
     
   - name: Install for CentOS
     yum : name=httpd state=latest
     when: ansible_os_family == "Redhat"
