---
- name: install
  hosts: all
  become: yes

  vars:
    source_file: ./mywebsite/index.html
    dest_file: /var/www/html

  tasks:
  - name: install
    yum: name=httpd state=latest

  - name: copy
    copy: src={{source_file}} dest={{dest_file}} mode=0555
    notify: restart    

  - name: start
    service: name=httpd state=started enabled=yes

  handlers:
  - name: restart
    service: name=httpd state=restarted
