version: '3.8'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
    container_name: es01
    restart: always
    environment:
      ELASTIC_PASSWORD: QWE123qwe
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /etc/localtime:/etc/localtime:ro
      - data:/usr/share/elasticsearch/data
      - logs:/usr/share/elasticsearch/logs
    network_mode: host
#    networks:
#      - elk_stack


volumes:
  data:
    driver_opts:
      type: none
      device: ../data
      o: bind
  logs:
    driver_opts:
      type: none
      device: ../logs
      o: bind

#networks:
#  elk_stack:
#    driver: bridge

